---
- name: Ansible ACI Demo Tenant 
  hosts: prod-01
  connection: local
  gather_facts: no
  vars:
   local_path: /home/administrator/ansible/CFGS/
   fvTenant: Hammergren
   BD_subnets:
    - 192.0.2.1/30
    - 192.0.2.5/30
    - 192.0.2.9/30
    - 192.0.2.13/30
    - 192.0.2.17/30
 
  tasks:
  - name:  Create Tenant,  A policy owner in the virtual fabric
    aci_install_config.py: xml_file={{local_path}}/fvTenant_Hammergren.xml URI=/api/mo/uni/tn-{{fvTenant}}.xml host={{hostname}} username=admin password={{password}}

  - name: Create fvCtx, private layer-3 network context 
    aci_install_config.py: xml_file={{local_path}}/fvCtx_Hammergren.xml URI=/api/mo/uni/tn-{{fvTenant}}.xml host={{hostname}} username=admin password={{password}}

  - name: Create fvBD, private layer-2 bridge domain(BD) consists of a set of physical or virtual ports and at least one subnet
    aci_install_config.py: xml_file={{local_path}}/fvBD_Hammergren.xml URI=/api/mo/uni/tn-{{fvTenant}}/BD-{{fvTenant}}.xml  host={{hostname}} username=admin password={{password}}
  
  - name: Create XML for subnets
    template: src={{local_path}}/templates/{{fvTenant}}_fvSubnet.j2 dest={{local_path}}/{{fvTenant}}_fvSubnet.xml

  - name: Add subnets fvSubnet to Bridge Domain
    aci_install_config.py: xml_file={{local_path}}/{{fvTenant}}_fvSubnet.xml URI=/api/mo/uni/tn-{{fvTenant}}/BD-{{fvTenant}}.xml  host={{hostname}} username=admin password={{password}}
