---
- name: Ansible ACI Demo of gathering facts using a class query
  hosts:  APIC-NGDC-East-1
  connection: local
  gather_facts: no

  tasks:
  - name: Class query for all known Tenants
    aci_gather_facts:  URI=/api/class/fvTenant.json host={{hostname}} username=admin password={{password}}

  - name: debug Tenant
    debug: var=fvTenant

  - name: Class query for all local users that are ACI trainers, the descr field contains the string "aci_trainer"
    aci_gather_facts:  URI=/api/class/aaaUser.json queryfilter=eq(aaaUser.descr,\"aci_trainer\") host={{hostname}} username=admin password={{password}}

  - name:  debug local users
    debug: var=item.name
    with_items: aaaUser

  - name:  Class query for powered on virtual machines
    aci_gather_facts: URI=/api/class/compVm.json queryfilter=eq(compVm.state,\"poweredOn\"  host={{hostname}} username=admin password={{password}}

  - name: debug virtual machines
    debug: var=item.os
    with_items: compVm


