---
- name: Ansible ACI Demo of gathering facts using a managed object  query
  hosts:  APIC-NGDC-East-1
  connection: local
  gather_facts: no

  vars:
    dn: comp/prov-VMware/ctrlr-[NGDC-VC]-VC_Cont

  tasks:
  - name: Managed Object (mo)  query for a VMware Vcenter managed object
    aci_gather_facts:
     URI: "/api/mo/{{dn}}.json"
     host: "{{hostname}}"
     username: admin
     password: "{{password}}"

  - name: debug vCenter object by class (all fields)
    debug: var=compCtrlr

  - name: debug  vCenter object variable hostOrIp
    debug: var=compCtrlr[0].hostOrIp

  - name: debug vCenter object variable model
    debug: var=compCtrlr[0].model

