---
- name: Ansible ACI Demo of using a class query with a filter to query all user tenants and apply a security policy
  hosts:  APIC-NGDC-East-1
  connection: local
  gather_facts: no
  vars:
   local_path: /home/administrator/ansible/CFGS
   filter: TCP_SMALL_SERVERS.xml

  tasks:
  - name: Class query for all known user tenants - ignore common, mgmt and infra
    aci_gather_facts:
     queryfilter: and (ne (fvTenant.name,"common"), ne(fvTenant.name,"mgmt"), ne(fvTenant.name,"infra"))
     URI: /api/class/fvTenant.json
     host: "{{hostname}}"
     username: admin
     password: "{{password}}"

  - name: debug Tenant list the tenants return from gathering facts from the controller
    debug: var=fvTenant

  - name:  Apply security policy filter to all tenants
    aci_install_config:
      xml_file: "{{local_path}}/{{filter}}"
      URI: "/api/mo/uni/tn-{{item.name}}.xml"
      host: "{{hostname}}"
      username: admin
      password: "{{password}}"
    with_items: fvTenant

  - name: Apply Service Contract to the ANSIBLE_DEMO tenant for testing
    aci_install_config:
      xml_file: "{{local_path}}/vzBrCP_ANSIBLE_DEMO.xml"
      URI: "/api/mo/uni/tn-ANSIBLE_DEMO.xml"
      host: "{{hostname}}"
      username: admin
      password: "{{password}}"

  - name: Get os of vm-107
    aci_gather_facts:
      URI: /api/mo/comp/prov-VMware/ctrlr-[NGDC-VC]-VC_Cont/vm-vm-107.json
      host: "{{hostname}}"
      username: admin
      password: "{{password}}"

  - name: Print os of vm-107
    debug: var=compVm[0].os

