---
# Demo playbook V3.0
- name: Configuring Tenant
  hosts: apic
  gather_facts: no

  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no
    tenant: NetDevOps
    vrf: vrf_ansible
    bd:
      name: bd_ansible_1
      ip: 10.10.10.1
      mask: 24
    app_profile: app1
    filter: Contract1_filter
    filter_entry: Contract1_entry
    contract: Contract1
    contract_subject: Subject1
    epg1: web_epg
    epg2: db_epg
    vmm_domain: Pod1

  tasks:
  - name: Create Tenant
    aci_tenant:
      <<: *aci_login
      tenant: '{{ tenant }}'
      description: 'tenant'
    delegate_to: localhost

  - name: Create VRF
    aci_vrf:
      <<: *aci_login
      tenant: '{{ tenant }}'
      vrf_name: '{{ vrf }}'
    delegate_to: localhost

  - name: Creating BD
    aci_bd:
      <<: *aci_login
      tenant: '{{ tenant }}'
      vrf: '{{ vrf }}'
      bd: '{{ bd.name }}'
    delegate_to: localhost

  - name: Create BD Subnet
    aci_bd_subnet:
      <<: *aci_login
      tenant: '{{ tenant }}'
      bd: '{{ bd.name }}'
      gateway: '{{ bd.ip }}'
      mask: '{{ bd.mask }}'
    delegate_to: localhost

  - name: Create AP
    aci_ap:
      <<: *aci_login
      tenant: '{{ tenant }}'
      app_profile: '{{ app_profile }}'
    delegate_to: localhost

  - name: Create web_epg
    aci_epg:
      <<: *aci_login
      tenant: '{{ tenant }}'
      app_profile: '{{ app_profile }}'
      epg: '{{ epg1 }}'
    delegate_to: localhost

  - name: Create db_epg
    aci_epg:
      <<: *aci_login
      tenant: '{{ tenant }}'
      app_profile: '{{ app_profile }}'
      epg: '{{ epg2 }}'
    delegate_to: localhost

  - name: Create Filter
    aci_filter:
      <<: *aci_login
      tenant: '{{ tenant }}'
      filter: '{{ filter }}'
    delegate_to: localhost

  - name: Create Filter Entry
    aci_filter_entry:
      <<: *aci_login
      tenant: '{{ tenant }}'
      filter: '{{ filter }}'
      filter_entry: '{{ filter_entry }}'
    delegate_to: localhost

  - name: Create Tenant Contract
    aci_contract:
      <<: *aci_login
      tenant: '{{ tenant }}'
      contract: '{{ contract }}'
      scope: tenant
    delegate_to: localhost

  - name: Create Contract Subject
    aci_contract_subject:
      <<: *aci_login
      tenant: '{{ tenant }}'
      contract: '{{ contract }}'
      contract_subject: '{{ contract_subject }}'
      reverse_filter: yes
    delegate_to: localhost

  - name: Bind Contract Subject to filter
    aci_contract_subject_to_filter:
      <<: *aci_login
      tenant: '{{ tenant }}'
      contract: '{{ contract }}'
      contract_subject: '{{ contract_subject }}'
      filter: '{{ filter }}'
    delegate_to: localhost

  - name: Bind EPG to Contract
    aci_epg_to_contract:
      <<: *aci_login
      tenant: '{{ tenant }}'
      epg: '{{ item.epg }}'
      app_profile: '{{ app_profile }}'
      contract: '{{ contract }}'
      contract_type: '{{ item.type }}'
    with_items:
    - epg: '{{ epg1 }}'
      type: consumer
    - epg: '{{ epg1 }}'
      type: provider
    - epg: '{{ epg2 }}'
      type: consumer
    - epg: '{{ epg2 }}'
      type: provider
    delegate_to: localhost