#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 World Wide Technology, Inc.
#      All rights reserved.
#
#      author: Joel W. King  World Wide Technology
#
- name: Ansible ACI Demo of gathering facts using a class query
  hosts: APIC 
  connection: local
  gather_facts: no
  vars:
   IPaddr: 192.0.2.5 

  tasks:
  - name: Decrypt the password file
    include_vars: "./passwords.yml"

  - name: Find the MAC address given an IP address 
    aci_gather_facts: 
     queryfilter: 'eq(fvCEp.ip, "{{IPaddr}}")' 
     URI: /api/class/fvCEp.json 
     host: "{{hostname}}"
     username: admin
     password: "{{password}}"

  - name: use msg format
    debug: msg=" ManagementIP {{ fvCEp[0].ip }}  mac {{ fvCEp[0].mac }} encap {{ fvCEp[0].encap }} "
    when:  fvCEp[0].ip is defined 
