#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 World Wide Technology, Inc.
#      All rights reserved.
#
#      author: Joel W. King,  World Wide Technology
#      name:  aci_ct_video.yml
#
- name: Ansible ACI clone tenant
  hosts:  APIC
  connection: local
  gather_facts: no

  vars:
   path:
     target: "./files/__security_policy.yml"
     source: "https://github.wwt.com/raw/{{APIC_uid}}/ACIxStart/master/security_policy.yml"

  tasks:
  - name: Decrypt the password file
    include_vars: "./passwords.yml"

  - name: Download the variables from Git
    uri:
      method: GET
      url: "{{path.source}}"
      dest: "{{path.target}}"
      validate_certs: no

  - name: Include the variables downloaded from Git
    include_vars: "{{path.target}}"

  - name: Clone a Tenant
    aci_clone_tenant:
     ihost:  "{{inventory_hostname}}"
     ohost:  "{{inventory_hostname}}" 
     username: "{{APIC_uid}}"
     password: "{{APIC_password}}"
     descr: "Cloned tenant from template {{fvTenant.template}} by {{APIC_uid}}"
     template: "{{fvTenant.template}}" 
     tenant: "{{fvTenant.name}}"
     # debug: on

  - name: Create XML file to update the security policy
    template:
      src: "./templates/fvAp/fvAp.j2"
      dest: "./files/__{{fvTenant.name}}_fvAp.xml"

  - name: Instanciate the XML file to the APIC
    aci_install_config:
      xml_file: "./files/__{{fvTenant.name}}_fvAp.xml"
      URI: "/api/mo/uni/tn-{{fvTenant.name}}.xml"
      host: "{{inventory_hostname}}"
      username: "{{APIC_uid}}"
      password: "{{APIC_password}}"
      # debug: on
